### ISSUE TITLE
 warmup_linear not working on BERT 0.6.2 vesrion

### ISSUE THREAD

**Issue by niranjan8129** [kamalkraj/BERT-NER#38]
Hi Kamal, Thank you sharing the code . I installed pytorch-pretrained-bert 0.6.2 version in my PC and run your code . I am getting below error while  executing  the code. Can you please guide me how to solve this issue using latest BERT 0.6.2 version?

   from pytorch_pretrained_bert.optimization import BertAdam, warmup_linear
ImportError: cannot import name 'warmup_linear' from 'pytorch_pretrained_bert.optimization' (C:\ProgramData\Anaconda3\lib\site-packages\pytorch_pretrained_bert\optimization.py)

 lr_this_step = args.learning_rate * **warmup_linear**(global_step/num_train_optimization_steps, args.warmup_proportion)

Is there other way we can change the code ?

Regards,
Niranjan

**Comment by kamalkraj** [comment]
Hi @niranjan8129 ,
Install pytorch-pretrained-bert 0.6.1 as per requirements.txt
why do you need 0.6.2 ?

**Comment by niranjan8129** [comment]
Thnak you Kamal.

Pytorch updating and adding new features, that is the reason I downloaded the latest one .

I proposed below code instead of last .what do you think?

**warmup_linear = WarmupLinearSchedule(warmup=args.warmup_proportion,
                                                 t_total=num_train_optimization_steps)
lr_this_step = args.learning_rate * warmup_linear.get_lr(global_step, args.warmup_proportion)**


lr_this_step = args.learning_rate * warmup_linear(global_step/num_train_optimization_steps, args.warmup_proportion)

**Comment by 0x01h** [comment]
Working version is **0.4.0**.

`pip3 install pytorch-pretrained-bert==0.4.0`

**Comment by niranjan8129** [comment]
Thank you a  lot. It works . Do you have knowledge how to make custom NER transformer . I am struggling a lot .
like 
John    is   traveling  to    Haridwar    for money
I-PER   O   I-TRA      O     I-LOC          O      I-CUR

John/I-PER        is/O         traveling /I-TRA         to/O          Haridwar/I-LOC         for/O        money/I-CUR



regards

**Comment by 0x01h** [comment]
@niranjan8129 Do you mean custom **IOB** annotation for your training data? If so, try to tokenize your sentences and search in your custom tags and apply regex for some specific cases.

**Comment by kamalkraj** [comment]
@niranjan8129 
For custom NER transformer :
- Create Data in the format of CoNLL-2003. Update datapath in `run_ner.py`
- Update the labels in `run_ner.py` as per your Custom tags and Train

**Comment by niranjan8129** [comment]
> @niranjan8129 Do you mean custom **IOB** annotation for your training data? If so, try to tokenize your sentences and search in your custom tags and apply regex for some specific cases.

@0x01h Do you mean custom IOB annotation for your training data? - **Yes**  , Thank your prompt response do you have examples ? My problem is how to identify Haridwar is a location or person if I do the custom word IOB annotations

**Comment by niranjan8129** [comment]
> @niranjan8129
> For custom NER transformer :
> 
> * Create Data in the format of CoNLL-2003. Update datapath in `run_ner.py`
> * Update the labels in `run_ner.py` as per your Custom tags and Train

Thank You @kamalkraj . My problem is how to identify **Haridwar**  is a location or person if I do the custom word  IOB annotations

**Comment by kamalkraj** [comment]
@niranjan8129 
I don't think you can just classify a word into a location or a person. NER is depended on the context of the word.
